import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-50">
         {/* Navbar */}
          <div className="h-[96px]">
            <Navbar/>
          </div>
          <div className="h-[calc(100vh-96px)]">
           {children}
          </div>
        </div>
      </body>
    </html>
  );
}
